-- SQL Script to insert dummy users and profiles into SriMatch database
-- Passwords are hashed as 'password123' using BCrypt: $2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv

-- Table: users
-- Amal Perera (User 1)
INSERT INTO users (first_name, last_name, email, password, role, is_email_verified, is_phone_verified, is_profile_completed, created_at, updated_at) 
VALUES ('Amal', 'Perera', 'test@example.com', '$2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv', 'USER', true, true, true, NOW(), NOW());

-- Nirmala Silva (User 2)
INSERT INTO users (first_name, last_name, email, password, role, is_email_verified, is_phone_verified, is_profile_completed, created_at, updated_at) 
VALUES ('Nirmala', 'Silva', 'nirmala@example.com', '$2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv', 'USER', true, true, true, NOW(), NOW());

-- Dinesh Rajapaksa (User 3)
INSERT INTO users (first_name, last_name, email, password, role, is_email_verified, is_phone_verified, is_profile_completed, created_at, updated_at) 
VALUES ('Dinesh', 'Rajapaksa', 'dinesh@example.com', '$2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv', 'USER', true, true, true, NOW(), NOW());

-- Kumari Bandara (User 4)
INSERT INTO users (first_name, last_name, email, password, role, is_email_verified, is_phone_verified, is_profile_completed, created_at, updated_at) 
VALUES ('Kumari', 'Bandara', 'kumari@example.com', '$2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv', 'USER', true, true, true, NOW(), NOW());

-- Sunil Fernando (User 5)
INSERT INTO users (first_name, last_name, email, password, role, is_email_verified, is_phone_verified, is_profile_completed, created_at, updated_at) 
VALUES ('Sunil', 'Fernando', 'sunil@example.com', '$2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv', 'USER', true, true, true, NOW(), NOW());

-- Priyanka Jayawardena (User 6)
INSERT INTO users (first_name, last_name, email, password, role, is_email_verified, is_phone_verified, is_profile_completed, created_at, updated_at) 
VALUES ('Priyanka', 'Jayawardena', 'priyanka@example.com', '$2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv', 'USER', true, true, true, NOW(), NOW());

-- Chaminda Gunawardena (User 7)
INSERT INTO users (first_name, last_name, email, password, role, is_email_verified, is_phone_verified, is_profile_completed, created_at, updated_at) 
VALUES ('Chaminda', 'Gunawardena', 'chaminda@example.com', '$2a$10$ByI6sqn.V.p47X8e.3y64eIBBvC9rP8L.x7yv7yv7yv7yv7yv7yv', 'USER', true, true, true, NOW(), NOW());

-- Table: profiles
-- Amal Perera Profile (user_id=1)
INSERT INTO profiles (user_id, gender, date_of_birth, marital_status, has_children, district, city, place_of_birth, religion, religious_practices, ethnicity, languages, horoscope_sign, education, field_of_study, profession, industry, employer, work_location, income_range, height, body_type, complexion, smoking, drinking, dietary_preferences, health_habits, lifestyle, family_background, cultural_values, family_involvement, wedding_preferences, about, interests, favorite_things, travel_preferences, partner_preferences, profile_images, primary_image_url, completion_score, profile_views, is_visible, created_at, updated_at)
VALUES (1, 'MALE', '1995-07-15', 'NEVER_MARRIED', false, 'Colombo', 'Colombo', 'Kandy', 'BUDDHIST', 'Regular temple visits', 'SINHALESE', '["Sinhala", "English", "Tamil (basic)"]', 'LEO', 'BACHELORS', 'Computer Engineering', 'Software Engineer', 'Information Technology', 'Tech Solutions Lanka', 'Colombo', '100k - 150k', 175, 'ATHLETIC', 'MEDIUM', 'NEVER', 'OCCASIONALLY', 'NON_VEGETARIAN', 'Regular gym, healthy diet', 'Early riser, organized, enjoys outdoors', 'Parents (both teachers), one younger sister', 'Modern with respect for traditions', 'Close-knit family, values family opinions', 'Traditional ceremony with modern elements', 'I\'m a software engineer who enjoys exploring new technologies and traveling around Sri Lanka.', '["Cricket", "Photography", "Reading", "Hiking", "Cooking"]', '{"food": "Rice and curry, Italian cuisine", "books": "Science fiction, biographies", "movies": "Christopher Nolan films", "places": "Ella, Mirissa, Sigiriya"}', 'Enjoys both local and international travel', '{"ageRange": [25, 32], "locationPreference": "Colombo or willing to relocate", "educationLevel": "Bachelor\'s degree or higher"}', '["https://images.unsplash.com/photo-1500648767791-00dcc994a43e", "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d"]', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e', 100, 0, true, NOW(), NOW());

-- Nirmala Silva Profile (user_id=2)
INSERT INTO profiles (user_id, gender, date_of_birth, marital_status, has_children, district, city, place_of_birth, religion, religious_practices, ethnicity, languages, horoscope_sign, education, field_of_study, profession, industry, employer, work_location, income_range, height, body_type, complexion, smoking, drinking, dietary_preferences, health_habits, lifestyle, family_background, cultural_values, family_involvement, wedding_preferences, about, interests, favorite_things, travel_preferences, partner_preferences, profile_images, primary_image_url, completion_score, is_visible, created_at, updated_at)
VALUES (2, 'FEMALE', '1997-03-22', 'NEVER_MARRIED', false, 'Kandy', 'Kandy', 'Kandy', 'BUDDHIST', 'Traditional Buddhist practices', 'SINHALESE', '["Sinhala", "English"]', 'PISCES', 'BACHELORS', 'Education', 'Teacher', 'Education', 'National School Kandy', 'Kandy', '50k - 100k', 162, 'SLIM', 'FAIR', 'NEVER', 'NEVER', 'NON_VEGETARIAN', 'Yoga, meditation', 'Traditional, family-oriented', 'Parents (father - businessman, mother - housewife), two siblings', 'Traditional values, respects elders', 'Very close with family', 'Traditional Buddhist ceremony', 'I am a passionate teacher who loves Sri Lankan culture and traditions.', '["Reading", "Cooking", "Traditional dance", "Teaching", "Gardening"]', '{"food": "Traditional Sri Lankan cuisine", "books": "Historical novels", "movies": "Drama, documentaries", "places": "Kandy lake, botanical gardens"}', 'Enjoys local cultural sites', '{"ageRange": [26, 35], "religionPreference": "Buddhist"}', '["https://images.unsplash.com/photo-1494790108377-be9c29b29330", "https://images.unsplash.com/photo-1589571894960-20bbe2828d0a"]', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330', 90, true, NOW(), NOW());

-- Dinesh Rajapaksa Profile (user_id=3)
INSERT INTO profiles (user_id, gender, date_of_birth, marital_status, has_children, district, city, place_of_birth, religion, religious_practices, ethnicity, languages, horoscope_sign, education, field_of_study, profession, industry, employer, work_location, income_range, height, body_type, complexion, smoking, drinking, dietary_preferences, health_habits, lifestyle, family_background, cultural_values, family_involvement, wedding_preferences, about, interests, favorite_things, travel_preferences, partner_preferences, profile_images, primary_image_url, completion_score, is_visible, created_at, updated_at)
VALUES (3, 'MALE', '1993-08-10', 'NEVER_MARRIED', false, 'Colombo', 'Colombo', 'Matara', 'HINDU', 'Regular temple visits', 'SINHALESE', '["Sinhala", "English", "Tamil"]', 'LEO', 'MASTERS', 'Computer Science', 'Software Engineer', 'Information Technology', 'Global Tech Solutions', 'Colombo', '150k - 200k', 178, 'ATHLETIC', 'MEDIUM', 'NEVER', 'SOCIALLY', 'NON_VEGETARIAN', 'Regular gym, cricket on weekends', 'Active, tech-savvy', 'Parents (father - engineer, mother - doctor), one brother', 'Modern with respect for traditions', 'Close with family but independent', 'Modern ceremony with traditional elements', 'Tech enthusiast working for a leading company in Colombo.', '["Cricket", "Photography", "Travel", "Technology", "Hiking"]', '{"food": "Seafood", "books": "Tech publications", "movies": "Action, sci-fi", "places": "Beaches,Mountains"}', 'Loves both local and international travel', '{"ageRange": [25, 32], "educationLevel": "Graduate"}', '["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d"]', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', 95, true, NOW(), NOW());

-- Kumari Bandara Profile (user_id=4)
INSERT INTO profiles (user_id, gender, date_of_birth, marital_status, has_children, district, city, place_of_birth, religion, religious_practices, ethnicity, languages, horoscope_sign, education, field_of_study, profession, industry, employer, work_location, income_range, height, body_type, complexion, smoking, drinking, dietary_preferences, health_habits, lifestyle, family_background, cultural_values, family_involvement, wedding_preferences, about, interests, favorite_things, travel_preferences, partner_preferences, profile_images, primary_image_url, completion_score, is_visible, created_at, updated_at)
VALUES (4, 'FEMALE', '1996-05-12', 'NEVER_MARRIED', false, 'Galle', 'Galle', 'Colombo', 'BUDDHIST', 'Moderate Buddhist practices', 'SINHALESE', '["Sinhala", "English"]', 'VIRGO', 'DOCTORATE', 'Medicine', 'Doctor', 'Healthcare', 'Galle General Hospital', 'Galle', '200k - 300k', 165, 'AVERAGE', 'FAIR', 'NEVER', 'OCCASIONALLY', 'NON_VEGETARIAN', 'Balanced diet, regular walks', 'Busy professional, values balance', 'Parents (father - businessman, mother - teacher), only child', 'Modern values', 'Close with parents', 'Simple ceremony', 'I\'m a dedicated doctor working at Galle General Hospital.', '["Medicine", "Volunteering", "Classical music", "Reading", "Beach walks"]', '{"food": "Healthy cuisine", "books": "Medical journals", "movies": "Dramas", "places": "Beaches"}', 'Enjoys relaxing getaways', '{"ageRange": [27, 35]}', '["https://images.unsplash.com/photo-1664575599736-c5197c684de0"]', 'https://images.unsplash.com/photo-1664575599736-c5197c684de0', 92, true, NOW(), NOW());

-- Sunil Fernando Profile (user_id=5)
INSERT INTO profiles (user_id, gender, date_of_birth, marital_status, has_children, district, city, place_of_birth, religion, religious_practices, ethnicity, languages, horoscope_sign, education, field_of_study, profession, industry, employer, work_location, income_range, height, body_type, complexion, smoking, drinking, dietary_preferences, health_habits, lifestyle, family_background, cultural_values, family_involvement, wedding_preferences, about, interests, favorite_things, travel_preferences, partner_preferences, profile_images, primary_image_url, completion_score, is_visible, created_at, updated_at)
VALUES (5, 'MALE', '1991-12-03', 'DIVORCED', true, 'Gampaha', 'Negombo', 'Negombo', 'CHRISTIAN', 'Regular church attendance', 'SINHALESE', '["Sinhala", "English"]', 'TAURUS', 'BACHELORS', 'Business Administration', 'Businessman', 'Fishing & Export', 'Fernando Enterprises', 'Negombo', '200k - 300k', 180, 'AVERAGE', 'MEDIUM', 'NEVER', 'OCCASIONALLY', 'NON_VEGETARIAN', 'Active due to work nature', 'Hardworking, family-focused', 'Large family with fishing business history', 'Traditional Christian values', 'Very involved, family business', 'Christian church wedding', 'Owner of a family business in Negombo.', '["Entrepreneurship", "Fishing", "Community service", "Sports", "Church activities"]', '{"food": "Seafood", "books": "Business", "places": "Coastal areas"}', 'Business travel, family vacations', '{"ageRange": [25, 35]}', '["https://images.unsplash.com/photo-1522529599102-193c0d76b5b6"]', 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6', 85, true, NOW(), NOW());

-- Priyanka Jayawardena Profile (user_id=6)
INSERT INTO profiles (user_id, gender, date_of_birth, marital_status, has_children, district, city, place_of_birth, religion, religious_practices, ethnicity, languages, horoscope_sign, education, field_of_study, profession, industry, employer, work_location, income_range, height, body_type, complexion, smoking, drinking, dietary_preferences, health_habits, lifestyle, family_background, cultural_values, family_involvement, wedding_preferences, about, interests, favorite_things, travel_preferences, partner_preferences, profile_images, primary_image_url, completion_score, is_visible, created_at, updated_at)
VALUES (6, 'FEMALE', '1994-09-18', 'NEVER_MARRIED', false, 'Colombo', 'Colombo', 'Colombo', 'BUDDHIST', 'Modern Buddhist', 'SINHALESE', '["Sinhala", "English"]', 'LIBRA', 'MASTERS', 'Finance', 'Bank Manager', 'Banking & Finance', 'National Bank of Ceylon', 'Colombo', '150k - 200k', 168, 'SLIM', 'FAIR', 'NEVER', 'SOCIALLY', 'NON_VEGETARIAN', 'Regular yoga', 'Career-focused but balanced', 'Parents, one brother', 'Modern with respect for traditions', 'Close with family', 'Modern ceremony', 'I\'m a career-oriented professional who also values work-life balance.', '["Finance", "Yoga", "Cooking", "Travel", "Reading"]', '{"food": "Mediterranean", "books": "Self-improvement", "places": "Beach resorts"}', 'Enjoys both local and international travel', '{"ageRange": [28, 38]}', '["https://images.unsplash.com/photo-1573496359142-b8d87734a5a2"]', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2', 92, true, NOW(), NOW());

-- Chaminda Gunawardena Profile (user_id=7)
INSERT INTO profiles (user_id, gender, date_of_birth, marital_status, has_children, district, city, place_of_birth, religion, religious_practices, ethnicity, languages, horoscope_sign, education, field_of_study, profession, industry, employer, work_location, income_range, height, body_type, complexion, smoking, drinking, dietary_preferences, health_habits, lifestyle, family_background, cultural_values, family_involvement, wedding_preferences, about, interests, favorite_things, travel_preferences, partner_preferences, profile_images, primary_image_url, completion_score, is_visible, created_at, updated_at)
VALUES (7, 'MALE', '1988-02-05', 'WIDOWED', true, 'Matara', 'Matara', 'Galle', 'HINDU', 'Moderate Hindu practices', 'SINHALESE', '["Sinhala", "English"]', 'CAPRICORN', 'BACHELORS', 'Civil Engineering', 'Civil Engineer', 'Construction & Infrastructure', 'Southern Development Authority', 'Matara', '100k - 150k', 183, 'AVERAGE', 'MEDIUM', 'NEVER', 'SOCIALLY', 'VEGETARIAN', 'Regular hiking', 'Balanced work and family focus', 'Parents (deceased), two sisters', 'Traditional values', 'Close with extended family', 'Simple ceremony', 'I work on infrastructure projects across Sri Lanka.', '["Architecture", "Cricket", "Hiking", "Sustainable development"]', '{"food": "Traditional Sri Lankan", "places": "Mountains, historical sites"}', 'Local travel', '{"ageRange": [28, 40]}', '["https://images.unsplash.com/photo-1492562080023-ab3db95bfbce"]', 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce', 88, true, NOW(), NOW());
