-- V1: Initial Schema for SriMatch
-- Based on JPA Entity definitions as of 2026-04-09

-- Users table
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(20) UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    is_email_verified BIT(1) DEFAULT 0,
    is_phone_verified BIT(1) DEFAULT 0,
    is_profile_completed BIT(1) DEFAULT 0,
    is_premium BIT(1) DEFAULT 0,
    premium_expiry_date DATETIME(6),
    referral_code_used VARCHAR(255),
    agree_to_marketing BIT(1) DEFAULT 0,
    agree_to_terms BIT(1) DEFAULT 0,
    last_login_at DATETIME(6),
    failed_login_attempts INT DEFAULT 0,
    account_locked_until DATETIME(6),
    is_deleted BIT(1) DEFAULT 0,
    deleted_at DATETIME(6),
    password_changed_at DATETIME(6),
    daily_like_limit INT DEFAULT 20,
    likes_today INT DEFAULT 0,
    last_like_reset DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    INDEX idx_email (email),
    INDEX idx_phone (phone_number),
    INDEX idx_role (role),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Profiles table
CREATE TABLE profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    gender VARCHAR(20),
    date_of_birth DATE,
    marital_status VARCHAR(20),
    has_children BIT(1),
    number_of_children INT,
    district VARCHAR(100),
    city VARCHAR(100),
    place_of_birth VARCHAR(100),
    religion VARCHAR(20),
    religious_practices TEXT,
    ethnicity VARCHAR(20),
    languages LONGTEXT,
    horoscope_sign VARCHAR(30),
    birth_star VARCHAR(50),
    horoscope_details TEXT,
    education VARCHAR(30),
    field_of_study VARCHAR(100),
    profession VARCHAR(100),
    industry VARCHAR(100),
    employer VARCHAR(200),
    work_location VARCHAR(100),
    income_range VARCHAR(50),
    height INT,
    body_type VARCHAR(20),
    complexion VARCHAR(20),
    smoking VARCHAR(20),
    drinking VARCHAR(20),
    dietary_preferences VARCHAR(30),
    health_habits TEXT,
    lifestyle TEXT,
    family_background TEXT,
    cultural_values TEXT,
    family_involvement TEXT,
    wedding_preferences TEXT,
    about TEXT,
    interests LONGTEXT,
    favorite_things LONGTEXT,
    travel_preferences TEXT,
    personality_traits VARCHAR(500),
    partner_preferences LONGTEXT,
    dealbreakers TEXT,
    profile_images LONGTEXT,
    primary_image_url VARCHAR(500),
    quiz_answers LONGTEXT,
    verification_status LONGTEXT,
    completion_score INT DEFAULT 0,
    profile_views INT DEFAULT 0,
    last_active_at DATETIME(6),
    is_visible BIT(1) DEFAULT 1,
    is_deleted BIT(1) DEFAULT 0,
    deleted_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_gender (gender),
    INDEX idx_religion (religion),
    INDEX idx_district (district),
    INDEX idx_marital_status (marital_status),
    INDEX idx_completion_score (completion_score),
    INDEX idx_last_active (last_active_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Refresh Tokens table
CREATE TABLE refresh_tokens (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(500) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    revoked BIT(1) DEFAULT 0,
    used BIT(1) DEFAULT 0,
    used_at DATETIME(6),
    user_agent VARCHAR(255),
    ip_address VARCHAR(45),
    CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_token (token),
    INDEX idx_user_id (user_id),
    INDEX idx_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- OTP Verifications table
CREATE TABLE otp_verifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    identifier VARCHAR(100) NOT NULL,
    otp VARCHAR(6) NOT NULL,
    otp_type VARCHAR(20) NOT NULL,
    is_verified BIT(1) DEFAULT 0,
    expires_at DATETIME(6) NOT NULL,
    attempts INT DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_identifier_type (identifier, otp_type),
    INDEX idx_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Likes table
CREATE TABLE likes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    message TEXT,
    expires_at DATETIME(6),
    responded_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    UNIQUE (sender_id, receiver_id),
    CONSTRAINT fk_like_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_like_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_sender_id (sender_id),
    INDEX idx_receiver_id (receiver_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Matches table
CREATE TABLE matches (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user1_id BIGINT NOT NULL,
    user2_id BIGINT NOT NULL,
    like_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    compatibility_score INT DEFAULT 0,
    user1_notified BIT(1) DEFAULT 0,
    user2_notified BIT(1) DEFAULT 0,
    matched_at DATETIME(6),
    expires_at DATETIME(6),
    ended_at DATETIME(6),
    end_reason VARCHAR(100),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    CONSTRAINT fk_match_user1 FOREIGN KEY (user1_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_match_user2 FOREIGN KEY (user2_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_user1_id (user1_id),
    INDEX idx_user2_id (user2_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_compatibility_score (compatibility_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Messages table
CREATE TABLE messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    status VARCHAR(20) NOT NULL DEFAULT 'SENT',
    is_read BIT(1) DEFAULT 0,
    read_at DATETIME(6),
    is_premium_message BIT(1) DEFAULT 0,
    is_delivered BIT(1) DEFAULT 0,
    delivered_at DATETIME(6),
    is_deleted_by_sender BIT(1) DEFAULT 0,
    is_deleted_by_receiver BIT(1) DEFAULT 0,
    media_url VARCHAR(500),
    media_type VARCHAR(50),
    media_size BIGINT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    CONSTRAINT fk_message_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE SET NULL,
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_match_id (match_id),
    INDEX idx_sender_id (sender_id),
    INDEX idx_receiver_id (receiver_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_is_premium_message (is_premium_message)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Notifications table
CREATE TABLE notifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    related_entity_id BIGINT,
    related_entity_type VARCHAR(50),
    action_url VARCHAR(500),
    is_read BIT(1) DEFAULT 0,
    read_at DATETIME(6),
    is_sent BIT(1) DEFAULT 0,
    sent_at DATETIME(6),
    is_delivered BIT(1) DEFAULT 0,
    delivered_at DATETIME(6),
    icon VARCHAR(50),
    color VARCHAR(20),
    created_at DATETIME(6) NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_is_read (is_read),
    INDEX idx_type (type),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Payments table
CREATE TABLE payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    payment_id VARCHAR(100) UNIQUE,
    order_id VARCHAR(100) UNIQUE,
    plan VARCHAR(20) NOT NULL,
    amount DOUBLE NOT NULL,
    currency VARCHAR(3),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(50),
    transaction_id VARCHAR(100),
    start_date DATETIME(6),
    end_date DATETIME(6),
    payment_details TEXT,
    failure_reason TEXT,
    refund_amount DOUBLE,
    refund_reason TEXT,
    refunded_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    completed_at DATETIME(6),
    CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_payment_id (payment_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Reports table
CREATE TABLE reports (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    reported_user_id BIGINT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    evidence_urls TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    admin_notes TEXT,
    resolved_at DATETIME(6),
    resolved_by BIGINT,
    action_taken VARCHAR(255),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_report_reported_user FOREIGN KEY (reported_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_report_resolver FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL,
    INDEX idx_reporter_id (reporter_id),
    INDEX idx_reported_user_id (reported_user_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Audit Logs table
CREATE TABLE audit_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    user_email VARCHAR(100),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50),
    entity_id BIGINT,
    details TEXT,
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    request_method VARCHAR(10),
    request_url VARCHAR(500),
    status_code INT,
    response_time_ms BIGINT,
    success BIT(1),
    created_at DATETIME(6) NOT NULL,
    INDEX idx_user_id (user_id),
    INDEX idx_action (action),
    INDEX idx_ip_address (ip_address),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
